Feature/#4/request estimate
AirconMoa/AirconMoa-Server pull request #13
Opened 2023-11-05 05:39 UTC by minjgziii

## 작업 내용
- 견적 요청서 작성
## 상세 내용
- 요청 예시
  - {
    "installInfo": "NEW_BUILDING",
    "installAddress": "서울시 강남구 테헤란로 1",
    "buildingType": "APARTMENT",    
    "amount": 2,
    "installationDate": "2023-12-01",
    "brand": "SAMSUNG"
}
- 응답 예시
  - {
    "requestEstimateId": 4,
    "installInfo": "NEW_BUILDING",
    "installAddress": "서울시 강남구 테헤란로 1",
    "buildingType": "APARTMENT",
    "amount": 2,
    "installationDate": "2023-12-01",
    "brand": "SAMSUNG",
    "user": null
}

- 추후, User와 로그인 관련 기능들이 완성되면 userId 부분 추가 및 수정 필요

## 관련 이슈
- [이슈 트래커]: #4

2023-11-05 06:36 UTC, jaewonLeeKOR requested changes

2023-11-05 06:36 UTC, jaewonLeeKOR commented on src/main/java/com/airconmoa/airconmoa/domain/RequestEstimate.java
> +@Table(name = "request_estimate")
name을 따로 명시하지 않았을때도 "request_estimate" 의 이름으로 테이블이 생성되지 않나요?

2023-11-05 06:36 UTC, jaewonLeeKOR commented on src/main/java/com/airconmoa/airconmoa/requestEstimate/controller/RequestEstimateController.java
> +    }
생성자 주입 형식을 사용하지 않고 AutoWired를 이용하여 직접 Bean을 등록한 이유가 따로 있나요?
RequiredArgsContructor 어노테이션을 사용하는게 더 낫지 않은가요?

2023-11-05 06:36 UTC, jaewonLeeKOR commented on src/main/java/com/airconmoa/airconmoa/requestEstimate/service/RequestEstimateService.java
> +    }
생성자 주입 형식을 사용하지 않고 AutoWired를 이용하여 직접 Bean을 등록한 이유가 따로 있나요?
RequiredArgsContructor 어노테이션을 사용하는게 더 낫지 않은가요?

2023-11-05 09:53 UTC, kick-sim commented on src/main/java/com/airconmoa/airconmoa/domain/RequestEstimate.java
> +@Table(name = "request_estimate")
그렇긴한데 저는 그냥 명시해줬었거든요 아마 제가 한거보고 일관성있게 맞추려고 한거같은데 다 빼는게 좋을까요?

2023-11-05 12:39 UTC, jaewonLeeKOR commented on src/main/java/com/airconmoa/airconmoa/domain/RequestEstimate.java
> +@Table(name = "request_estimate")
그럼 어떻게 사용할지만 정해서 통일성 있게 맞추는 방향으로 생각해보죠

2023-11-06 02:41 UTC, minjgziii commented on src/main/java/com/airconmoa/airconmoa/requestEstimate/controller/RequestEstimateController.java
> +    }
수정하겠습니다~

2023-11-06 06:35 UTC, jaewonLeeKOR approved these changes
고생하셨어요

2023-11-07 05:46 UTC, kick-sim approved these changes
수고하셧어요

2023-11-10 07:22 UTC, jaewonLeeKOR commented
CI 파이프라인에서 오류가 나는건 다른 PR 에서 빌드가 가능하지 않은 상태로 머지를 해서 생기는 현상이에요.
다른 브랜치를 머지하면서 해당 부분이 수정되었으니 check가 fail 되었지만 머지하면 배포가 정상적으로 될거 같아요.
머지 부탁드려요~ @minjgziii

2023-11-10 09:48 UTC, merged