견적서 생성, 단건 조회, 수정 API
AirconMoa/AirconMoa-Server pull request #14
Opened 2023-11-05 06:30 UTC by jaewonLeeKOR

## 작업 내용
- 견적서 생성, 단건 조회, 수정 API 구현
## 상세 내용
- 견적서 엔티티
- 견적서 생성
- 견적서 단건 조회
- 견적서 수정
## 관련 이슈
- FEAT #5

2023-11-05 10:06 UTC, kick-sim requested changes

2023-11-05 10:06 UTC, kick-sim commented on src/main/java/com/airconmoa/airconmoa/domain/Company.java
> +    private User adminUser;
adminUser는 어떤 필드인가요??

2023-11-05 12:38 UTC, jaewonLeeKOR commented on src/main/java/com/airconmoa/airconmoa/domain/Company.java
> +    private User adminUser;
업체측의 엔티티와 로그인하는 주체인 user를 다른 엔티티로 보았습니다. 업체를 관리하기 위해 로그인하는 사용자를 의미합니다.
견적서에 대한 API를 제공시에 업체에 대한 정보가 빠지면 안된다고 생각하여 해당 부분 함께 구현하였습니다.
이 부분을 개발할 때 수정해서 개발하면 될 것 같아요.

2023-11-06 02:38 UTC, minjgziii commented on src/main/java/com/airconmoa/airconmoa/estimate/controller/EstimateController.java
> +@RequestMapping("/api/estimate")
요청 url에 /api는 생략해도 되지 않을까용?

2023-11-06 02:50 UTC, jaewonLeeKOR commented on src/main/java/com/airconmoa/airconmoa/estimate/controller/EstimateController.java
> +@RequestMapping("/api/estimate")
이부분은 하나의 서버에서 웹페이지도 제공하고 API 서비스도 제공하는 경우 "/api" prefix를 붙여 API endpoint path임을 명시적으로 사용하기 위해 사용하는걸로 알고 있는데요
@kick-sim 가 user 엔티티 접근 endpoint path로 이 방식을 사용하여서 동일하게 적용해 봤어요
이부분도 협의를 해보고 하나로 통일해서 정하면 될거 같아요~!

2023-11-06 06:45 UTC, minjgziii commented on src/main/java/com/airconmoa/airconmoa/estimate/controller/EstimateController.java
> +@RequestMapping("/api/estimate")
넵~!

2023-11-06 13:38 UTC, minjgziii approved these changes
고생하셨습니다!

2023-11-07 05:46 UTC, kick-sim commented on src/main/java/com/airconmoa/airconmoa/domain/Company.java
> +    private User adminUser;
업체가 하나의 유저처럼 로그인하는 방식으로 기획해서 수정하는게 좋을거같습니다! User는 사용자 Company는 업체 둘은 별개로 생각하면 될거같아요

2023-11-09 11:10 UTC, jaewonLeeKOR commented on src/main/java/com/airconmoa/airconmoa/domain/Company.java
> +    private User adminUser;
네 여기서는 Company 부분을 중점으로 구현한게 아니라 수정하면 될거같아요 adminUser 부분만 빼면 되겠죠?

2023-11-12 11:46 UTC, jaewonLeeKOR commented
@kick-sim 확인해주세요~

2023-11-13 06:36 UTC, kick-sim approved these changes
수고하셨습니다

2023-11-13 06:36 UTC, kick-sim commented on src/main/java/com/airconmoa/airconmoa/domain/Company.java
> +    private User adminUser;
추가되야할 필드가 있어서 제 pr(#15)에 있는 Company 클래스로 통일합시다

2023-11-13 12:24 UTC, merged